name: mi-mongodb

# Kubernetes namespace to install into (can be overridden)
namespace: ecuaalejo2013-dev


replicaCount: 2

auth:
  enabled: false

# Config mínimo que exige el chart
config:
  content: |
    net:
      bindIpAll: true
      port: 27017
    replication:
      replSetName: rs0

# Servicio interno (no LB/NodePort)
service:
  type: ClusterIP
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017

# Puerto del contenedor (algunos charts lo usan)
containerPorts:
  mongodb: 27017

# Desactiva persistencia en sandbox para evitar problemas de PVC
persistence:
  enabled: false

# Seguridad compatible con OpenShift (sin "enabled:" aquí)
podSecurityContext:
  # OpenShift inyecta un UID arbitrario; no fuerces un UID concreto.
  fsGroupChangePolicy: "OnRootMismatch"

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false   # Mongo necesita escribir
  capabilities:
    drop: ["ALL"]