name: mi-mongodb

# Kubernetes namespace to install into (can be overridden)
namespace: ecuaalejo2013-dev


auth:
  enabled: false

config:
  content: |
    net:
      bindIpAll: true
      port: 27017
    replication:
      replSetName: rs0

# elige UNA de estas variantes y borra la otra
service:
  type: ClusterIP
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017

containerPorts:
  mongodb: 27017

# sin "enabled:" aquí
podSecurityContext:
  runAsNonRoot: true
  fsGroup: 1001

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop: ["ALL"]